version: '3'

services:
  odoo:
    container_name: odoo_${PROJECT}
    image: odoo:${ODOO_VERSION}
    restart: always
    ports:
      - "${PORT}:8069"
    depends_on:
      - postgres
    volumes:
      - ./odoo/config/:/etc/odoo
      - ./odoo/addons/:/mnt/extra-addons
      - ./odoo/logs/:/var/log/odoo
    environment:
      - HOST=postgres
      - USER=${DB_USER:-odoo}
      - PASSWORD=${DB_PASSWORD}

  postgres:
    container_name: postgres_${PROJECT}
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_POSTGRES:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER:-odoo}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /data/${PROJECT}:/var/lib/postgresql/data/pgdata

volumes:
  postgres: {}
